[package]
name = 'entropic'
version = '0.1.0'
authors = ['Anton Bulakh <self@necauqua.dev>']
edition = '2018'

[dependencies]
libc = '0.2'
termios = '0.3'
signal-hook = '0.3'
term_size = '1.0.0-beta1' # ugh, who names their crates with underscores
crossbeam-channel = '0.5'
color-backtrace = '0.5'

